# Original workflow file taken from: https://github.com/learn-github-actions/getting-started-github-actions/blob/main/.github/workflows/github-actions-secret.yml
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: Simple GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  simple-secrets-in-github-actions:
    runs-on: windows-latest
    
    # The "Simple GitHub Actions Secret" example has five separate parts.
    # Parts 1 to 3 give you a quick idea on how to echo out and work with
    # GitHub Action secrets in a bash shell.
    # Part 4 illustrates how to use GitHub Action secrets as input arguments
    # for simple applications in R.
    
    steps:
    
      # Part 1 - Print unmasked GitHub secrets to console
      - name: Part 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "My GitHub Action Secret is:  "
          echo "${{ secrets.MY_SECRET }}"
          
      # Part 2 - Use a GitHub Actions secret variable in a bash shell
      - name: Part 2 - GitHub Action if statement (true)
        env: 
          WHATS_MY_SECRET: ${{ secrets.MY_SECRET  }}
        if:  env.WHATS_MY_SECRET == 'I never share everything I know.'
        run: echo "I know what the secret is!"

      # Part 3 - GitHub Actions if statement with a secret environment variable
      - name: Part 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          WHATS_MY_SECRET: ${{ secrets.MY_SECRET  }}
        if:  env.WHATS_MY_SECRET != 'I never share everything I know.'
        run: echo "I was wrong thinking I knew the secret!"
        
      # Part 4 - GitHub Action secrets in R
      - name: Part 4 - GitHub Action in R
        shell: Rscript {0}
        run: |
          my_secret <- "${{ secrets.MY_SECRET }}"
          if(my_secret == 'I never share everything I know.') {
            print("I know what the secret is!")
          }          
